skips:
  - B101  # Skip the "assert used" warning
  - B110  # Skip "Try, Except, Pass" warning (common in bot logic)

severity: MEDIUM 
confidence: HIGH  

targets:
  - cogs # all cogs directory commands here 
  - main.py  # Main bot entry point
